# ===========================
# Configuracao do Banco Oracle
# ===========================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm566067
spring.datasource.password=060606
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===========================
# Configuracao JPA / Hibernate
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Configuracao do Servidor
# ===========================
server.port=8080
